In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [3]:
# Load the data
Hdf = pd.read_csv('Resources/Hdata.csv')

# Display the first few rows of the DataFrame to verify
Hdf.head()

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,MDG_0000000003,Adolescent birth rate (per 1000 women),text,EUR,Europe,Country,HRV,Croatia,Year,2023,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Registration National Statistics,EN,2024-03-26 00:00:00
1,MDG_0000000003,Adolescent birth rate (per 1000 women),text,EUR,Europe,Country,HRV,Croatia,Year,2023,...,NaN,NaN,NaN,NaN,NaN,6.7,NaN,Registration National Statistics,EN,2024-03-26 00:00:00
2,MDG_0000000003,Adolescent birth rate (per 1000 women),text,EMR,Eastern Mediterranean,Country,YEM,Yemen,Year,2023,...,NaN,NaN,NaN,NaN,NaN,77.0,NaN,Yemen 2022-2023 Multiple Indicator Cluster Survey,EN,2024-03-26 00:00:00
3,MDG_0000000003,Adolescent birth rate (per 1000 women),text,GLOBAL,Global,Country,MAC,"China, Macao Special Administrative Region",Year,2022,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Registration National Statistics & WPP2022,EN,2024-03-26 00:00:00
4,MDG_0000000003,Adolescent birth rate (per 1000 women),text,EUR,Europe,Country,DNK,Denmark,Year,2022,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Registration National Statistics & WPP2022,EN,2024-03-26 00:00:00

In [4]:
Hdf_cleaned = Hdf[['ParentLocation', 'Location', 'Period', 'Dim2', 'Value', 'FactComments']]

Hdf_cleaned.head()

,ParentLocation,Location,Period,Dim2,Value,FactComments
0,Europe,Croatia,2023,10-14 years,0.0,Registration National Statistics
1,Europe,Croatia,2023,15-19 years,6.7,Registration National Statistics
2,Eastern Mediterranean,Yemen,2023,15-19 years,77.0,Yemen 2022-2023 Multiple Indicator Cluster Survey
3,Global,"China, Macao Special Administrative Region",2022,10-14 years,0.0,Registration National Statistics & WPP2022
4,Europe,Denmark,2022,10-14 years,0.0,Registration National Statistics & WPP2022

In [5]:
# Create a copy of the DataFrame
hDf_cleaned = Hdf_cleaned.copy()

# Rename the 'Value' column to 'Adolescent birth rate (per 1000 women)'
hDf_cleaned.rename(columns={'Value': 'Adolescent birth rate (per 1000 women)', 'Dim2': 'Age-group'}, inplace=True)

In [6]:
hDf_cleaned.head()

,ParentLocation,Location,Period,Age-group,Adolescent birth rate (per 1000 women),FactComments
0,Europe,Croatia,2023,10-14 years,0.0,Registration National Statistics
1,Europe,Croatia,2023,15-19 years,6.7,Registration National Statistics
2,Eastern Mediterranean,Yemen,2023,15-19 years,77.0,Yemen 2022-2023 Multiple Indicator Cluster Survey
3,Global,"China, Macao Special Administrative Region",2022,10-14 years,0.0,Registration National Statistics & WPP2022
4,Europe,Denmark,2022,10-14 years,0.0,Registration National Statistics & WPP2022

In [7]:
# Export the cleaned data to CSV
hDf_cleaned.to_csv("Output/Halima.csv", index=False)

In [8]:
# Group by 'Location' (country) and find the maximum Adolescent birth rate
max_birth_rate =hDf_cleaned.groupby('Location')['Adolescent birth rate (per 1000 women)'].max()

# Find the country with the highest Adolescent birth rate
highest_birth_rate_country = max_birth_rate.idxmax()
highest_birth_rate_value = max_birth_rate.max()

print(f"The country with the highest Adolescent birth rate (per 1000 women) is {highest_birth_rate_country} with a rate of {highest_birth_rate_value}")

The country with the highest Adolescent birth rate (per 1000 women) is Central African Republic with a rate of 184.4

In [9]:
min_birth_rate = hDf_cleaned.groupby('Location')['Adolescent birth rate (per 1000 women)'].min()

# Find the country with the lowest Adolescent birth rate
lowest_birth_rate_country = min_birth_rate.idxmin()
lowest_birth_rate_value = min_birth_rate.min()

print(f"The country with the lowest Adolescent birth rate (per 1000 women) is {lowest_birth_rate_country} with a rate of {lowest_birth_rate_value}")

The country with the lowest Adolescent birth rate (per 1000 women) is Algeria with a rate of 0.0

In [10]:
highest_rate = hDf_cleaned.sort_values(by='Adolescent birth rate (per 1000 women)', ascending=False)

highest_rate.head(10)

,ParentLocation,Location,Period,Age-group,Adolescent birth rate (per 1000 women),FactComments
310,Africa,Central African Republic,2018,15-19 years,184.4,Central African Republic 2018-2019 Multiple In...
409,Africa,Equatorial Guinea,2010,15-19 years,176.0,Equatorial Guinea 2011 Demographic and Health ...
386,Africa,Angola,2014,15-19 years,162.7,Angola 2015-2016 Demographic and Health Survey
418,Africa,South Sudan,2008,15-19 years,158.1,South Sudan 2010 Household Health Survey Secon...
149,Africa,Mozambique,2021,15-19 years,158.0,Mozambique 2022-2023 Demographic and Health Su...
233,Africa,Niger,2020,15-19 years,150.3,Niger 2021 Malaria Indicator Survey
231,Africa,Mali,2020,15-19 years,144.8,Mali 2021 Malaria Indicators Survey
267,Africa,Madagascar,2019,15-19 years,143.0,Madagascar 2021 Demographic and Health Survey
307,Africa,Chad,2018,15-19 years,138.5,Chad 2019 Multiple Indicator Cluster Survey
306,Africa,Malawi,2018,15-19 years,135.6,Malawi 2019-2020 Multiple Indicator Cluster Su...

In [11]:
# Sort the DataFrame in ascending order based on 'Adolescent birth rate (per 1000 women)'
lowest_rate = hDf_cleaned.sort_values(by='Adolescent birth rate (per 1000 women)', ascending=True)

# Display the sorted DataFrame
lowest_rate.head(10)

,ParentLocation,Location,Period,Age-group,Adolescent birth rate (per 1000 women),FactComments
0,Europe,Croatia,2023,10-14 years,0.0,Registration National Statistics
74,South-East Asia,Bhutan,2021,10-14 years,0.0,Registration National Statistics & WPP2022
73,Americas,Bermuda,2021,10-14 years,0.0,Registration National Statistics & WPP2022
72,Europe,Belgium,2021,10-14 years,0.0,Registration Eurostat
71,Europe,Azerbaijan,2021,10-14 years,0.0,Registration National Statistics & WPP2022
70,Europe,Austria,2021,10-14 years,0.0,Registration Eurostat
211,Europe,Armenia,2020,10-14 years,0.0,Registration Eurostat
212,Americas,Montserrat,2020,10-14 years,0.0,Registration National Statistics & WPP2022
213,South-East Asia,Nepal,2020,10-14 years,0.0,NepalÂ 2022Â DemographicÂ andÂ HealthÂ Survey
254,Eastern Mediterranean,Bahrain,2019,10-14 years,0.0,Registration National Statistics & WPP2022

In [12]:
# Count occurrences of Age-group values
age_group_counts = hDf_cleaned['Age-group'].value_counts()

# Display the counts
print("Age-group counts:")
print(age_group_counts)

Age-group counts:
Age-group
15-19 years    223
10-14 years    215
Name: count, dtype: int64

In [13]:
hDf_cleaned.dtypes

ParentLocation                             object
Location                                   object
Period                                      int64
Age-group                                  object
Adolescent birth rate (per 1000 women)    float64
FactComments                               object
dtype: object

In [14]:
## HS
# Add Starting_Year and Year_Ending columns
hDf_cleaned['Starting_Year'] = hDf_cleaned['Period']
hDf_cleaned['Year_Ending'] = hDf_cleaned['Period']

# Define the function to categorize Period into ranges
def categorize_period(period):
    if 2003 <= period <= 2005:
        return '2003-2005'
    elif 2006 <= period <= 2008:
        return '2006-2008'
    elif 2009 <= period <= 2011:
        return '2009-2011'
    elif 2012 <= period <= 2014:
        return '2012-2014'
    elif 2015 <= period <= 2017:
        return '2015-2017'
    elif 2018 <= period <= 2020:
        return '2018-2020'
    elif 2021 <= period <= 2023:
        return '2021-2023'
    else:
        return 'Other'  # If the period does not fall into these ranges

# Add Period_Range column
hDf_cleaned['Period_Range'] = hDf_cleaned['Period'].apply(categorize_period)

In [15]:
hDf_cleaned.head()

,ParentLocation,Location,Period,Age-group,Adolescent birth rate (per 1000 women),FactComments,Starting_Year,Year_Ending,Period_Range
0,Europe,Croatia,2023,10-14 years,0.0,Registration National Statistics,2023,2023,2021-2023
1,Europe,Croatia,2023,15-19 years,6.7,Registration National Statistics,2023,2023,2021-2023
2,Eastern Mediterranean,Yemen,2023,15-19 years,77.0,Yemen 2022-2023 Multiple Indicator Cluster Survey,2023,2023,2021-2023
3,Global,"China, Macao Special Administrative Region",2022,10-14 years,0.0,Registration National Statistics & WPP2022,2022,2022,2021-2023
4,Europe,Denmark,2022,10-14 years,0.0,Registration National Statistics & WPP2022,2022,2022,2021-2023

In [19]:
adolescent_birth= pd.read_csv('Output/adolescent_births.csv')

In [20]:
adolescent_birth.head()

,ParentLocation,Location,Age-group,Adolescent_birth_rate,FactComments,Starting_Year,Year_Ending,Period_Range
0,Europe,Croatia,10-14 years,0.0,Registration National Statistics,2023,2023,2021-2023
1,Europe,Croatia,15-19 years,6.7,Registration National Statistics,2023,2023,2021-2023
2,Eastern Mediterranean,Yemen,15-19 years,77.0,Yemen 2022-2023 Multiple Indicator Cluster Survey,2023,2023,2021-2023
3,Global,"China, Macao Special Administrative Region",10-14 years,0.0,Registration National Statistics & WPP2022,2022,2022,2021-2023
4,Europe,Denmark,10-14 years,0.0,Registration National Statistics & WPP2022,2022,2022,2021-2023

In [28]:
average_birth_rate = adolescent_birth.groupby('Period_Range')['Adolescent_birth_rate'].mean()
average_birth_rate

Period_Range
2003-2005       17.600000
2006-2008       28.453333
2009-2011       28.580000
2012-2014       32.322727
2015-2017       34.072549
2018-2020       30.675410
2021-2023       11.580952
Out of Range    37.250000
Name: Adolescent_birth_rate, dtype: float64

In [31]:
# Group by Location and calculate mean Adolescent_birth_rate
birth_rate_vs_location = adolescent_birth.groupby('Location')['Adolescent_birth_rate'].mean()
birth_rate_vs_location

Location
Afghanistan                                                 40.00
Albania                                                      6.05
Algeria                                                      5.50
American Samoa                                              18.35
Andorra                                                      0.25
                                                            ...
Wallis and Futuna Islands                                    5.00
Yemen                                                       39.00
Zambia                                                      68.75
Zimbabwe                                                    43.95
occupied Palestinian territory, including east Jerusalem    21.40
Name: Adolescent_birth_rate, Length: 223, dtype: float64

In [16]:
family_planning = pd.read_csv('Output/family_planning.csv')

In [17]:
family_planning.head()

,IndicatorCode,Indicator,Patents_Continent_Code,ParentLocation_Continent,Country_Code,Country,Gender,Age_Group,Planning_Value_Rate,FactComments,Language_Code,Starting_Year,Year_Ending,Period_Range
0,SDGFPALL,Women of reproductive age (aged 15-49 years) w...,AFR,Africa,UGA,Uganda,Female,15-49 years,65.5,The global indicator represents all women of r...,EN,2021,2021,2021-2023
1,SDGFPALL,Women of reproductive age (aged 15-49 years) w...,AFR,Africa,NER,Niger,Female,15-49 years,36.9,Niger 2021 PMA Survey Phase 1,EN,2020,2021,2021-2023
2,SDGFPALL,Women of reproductive age (aged 15-49 years) w...,AFR,Africa,BFA,Burkina Faso,Female,15-49 years,58.2,Burkina Faso 2021 PMA Survey Phase 2,EN,2020,2021,2021-2023
3,SDGFPALL,Women of reproductive age (aged 15-49 years) w...,WPR,Western Pacific,VNM,Viet Nam,Female,15-49 years,72.1,The global indicator represents all women of r...,EN,2020,2021,2021-2023
4,SDGFPALL,Women of reproductive age (aged 15-49 years) w...,AFR,Africa,CIV,Cote d'Ivoire,Female,15-49 years,46.1,CÃ´te d'Ivoire 2020 PMA Survey Phase 1,EN,2020,2020,2018-2020

In [35]:
average_plnning_vs_location = family_planning.groupby('Country')['Planning_Value_Rate'].mean()
average_plnning_vs_location

Country
Afghanistan                                                 42.1
Albania                                                      6.3
Algeria                                                     66.3
Angola                                                      29.8
Argentina                                                   80.3
                                                            ...
Viet Nam                                                    72.1
Yemen                                                       40.5
Zambia                                                      65.9
Zimbabwe                                                    84.8
occupied Palestinian territory, including east Jerusalem    61.0
Name: Planning_Value_Rate, Length: 136, dtype: float64

In [33]:
average_family_plnning = family_planning.groupby('Period_Range')['Planning_Value_Rate'].mean()
average_family_plnning

Period_Range
2003-2005       71.733333
2006-2008       66.933333
2009-2011       51.900000
2012-2014       58.914286
2015-2017       60.446667
2018-2020       55.712698
2021-2023       58.175000
Out of Range    96.600000
Name: Planning_Value_Rate, dtype: float64

In [21]:
merged_data = pd.merge(adolescent_birth, family_planning, 
                       left_on='Location', 
                       right_on='Country')

In [26]:
mean_birth_rate = adolescent_birth['Adolescent_birth_rate'].mean()
print(mean_birth_rate)

21.72579908675799

In [22]:
merged_data.head()

,ParentLocation,Location,Age-group,Adolescent_birth_rate,FactComments_x,Starting_Year_x,Year_Ending_x,Period_Range_x,IndicatorCode,Indicator,...,Country_Code,Country,Gender,Age_Group,Planning_Value_Rate,FactComments_y,Language_Code,Starting_Year_y,Year_Ending_y,Period_Range_y
0,Eastern Mediterranean,Yemen,15-19 years,77.0,Yemen 2022-2023 Multiple Indicator Cluster Survey,2023,2023,2021-2023,SDGFPALL,Women of reproductive age (aged 15-49 years) w...,...,YEM,Yemen,Female,15-49 years,40.5,The global indicator represents all women of r...,EN,2013,2013,2012-2014
1,Eastern Mediterranean,Yemen,10-14 years,1.0,Yemen 2013 Demographic and Health Survey,2012,2012,2012-2014,SDGFPALL,Women of reproductive age (aged 15-49 years) w...,...,YEM,Yemen,Female,15-49 years,40.5,The global indicator represents all women of r...,EN,2013,2013,2012-2014
2,Europe,Kazakhstan,10-14 years,0.0,Registration National Statistics & WPP2022,2022,2022,2021-2023,SDGFPALL,Women of reproductive age (aged 15-49 years) w...,...,KAZ,Kazakhstan,Female,15-49 years,73.2,The global indicator represents all women of r...,EN,2018,2018,2018-2020
3,Europe,Kazakhstan,15-19 years,19.7,Registration National Statistics,2022,2022,2021-2023,SDGFPALL,Women of reproductive age (aged 15-49 years) w...,...,KAZ,Kazakhstan,Female,15-49 years,73.2,The global indicator represents all women of r...,EN,2018,2018,2018-2020
4,Europe,Montenegro,10-14 years,0.0,Registration National Statistics & WPP2022,2022,2022,2021-2023,SDGFPALL,Women of reproductive age (aged 15-49 years) w...,...,MNE,Montenegro,Female,15-49 years,32.9,Montenegro 2018 Multiple Indicator Cluster Survey,EN,2018,2018,2018-2020

In [23]:
# Filter relevant columns
relevant_data = merged_data[['Adolescent_birth_rate', 'Planning_Value_Rate']]

# Calculate correlation
correlation = relevant_data.corr()

In [25]:
# Display correlation
correlation

                       Adolescent_birth_rate  Planning_Value_Rate
Adolescent_birth_rate               1.000000            -0.200183
Planning_Value_Rate                -0.200183             1.000000